name: Tests

on:
  push:

jobs:
  tests:
    name: test ${{matrix.db}} ruby-${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3']
        db: ['postgresql', 'mysql2']
      fail-fast: false

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: redmine_test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: redmine_test
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and configure environment
        run: |
          sudo apt-get update
          sudo apt-get install --yes --quiet ghostscript gsfonts locales bzr cvs
          sudo locale-gen en_US # for bazaar non ascii test

      - name: Allow imagemagick to read PDF files
        run: |
          echo '<policymap>' > policy.xml
          echo '<policy domain="coder" rights="read | write" pattern="PDF" />' >> policy.xml
          echo '</policymap>' >> policy.xml
          sudo rm /etc/ImageMagick-6/policy.xml
          sudo mv policy.xml /etc/ImageMagick-6/policy.xml

      - name: Prepare Redmine database configuration
        run: |
          cat > config/database.yml <<EOF
          test:
            adapter: ${{ matrix.db }}
            database: redmine_test
            username: root
            password: root
            host: 127.0.0.1
          EOF

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run prepare test environment
        env:
          RAILS_ENV: test
          SCMS: subversion,git,git_utf8,filesystem,bazaar,cvs
        run: |
          bundle exec rake ci:about
          bundle exec rake ci:setup
          bundle exec rake db:environment:set

      - name: Run tests
        run: |
          bin/rails test
          bin/rails test:autoload

      - name: Run bazaar non ascii test
        env:
          LANG: en_US.ISO8859-1
          LC_ALL: en_US.ISO8859-1
        run: |
          bin/rails test test/unit/repository_bazaar_test.rb

      - name: Run autoload test
        run: |
          bin/rails test:autoload

      # System tests use Chrome and ChromeDriver installed on the GitHub Actions Ubuntu image.
      # They are generally updated to the latest stable versions.
      - name: Run system tests
        run: |
          google-chrome --version
          bin/rails test:system
        env:
          GOOGLE_CHROME_OPTS_ARGS: headless,disable-gpu,no-sandbox,disable-dev-shm-usage
        # System tests might still be a bit unstable, so for now, even if a system test fails,
        # output the results and consider the overall test as successful.
        continue-on-error: true

      - name: Upload system test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: system-test-screenshots-ruby${{ matrix.ruby }}-${{ matrix.db }}
          path: tmp/screenshots
          if-no-files-found: ignore
